### ISSUE TITLE
Get : unsupported protocol scheme ""

### ISSUE THREAD

**Issue by steevegldev** [openfaas/faas-swarm#62] opened 2019-11-01 02:11 UTC
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

http://localhost:8080/ui/ return: Get : unsupported protocol scheme ""

faas_gateway log
```
2019/11/01 02:02:29 HTTP Read Timeout: 5m5s,
2019/11/01 02:02:29 HTTP Write Timeout: 5m5s,
2019/11/01 02:02:29 Binding to external function provider: http://faas-swarm:8080/,
2019/11/01 02:02:29 Async enabled: Using NATS Streaming.,
2019/11/01 02:02:29 Opening connection to nats://nats:4222,
2019/11/01 02:02:29 Connect: nats://nats:4222,
2019/11/01 02:02:30 ExternalAuthHandler: Get : unsupported protocol scheme "",
2019/11/01 02:02:31 ExternalAuthHandler: Get : unsupported protocol scheme "",
2019/11/01 02:02:32 ExternalAuthHandler: Get : unsupported protocol scheme "",
2019/11/01 02:02:32 ExternalAuthHandler: Get : unsupported protocol scheme "",
2019/11/01 02:02:32 ExternalAuthHandler: Get : unsupported protocol scheme "",
2019/11/01 02:02:32 ExternalAuthHandler: Get : unsupported protocol scheme "",
2019/11/01 02:02:32 ExternalAuthHandler: Get : unsupported protocol scheme "",
2019/11/01 02:02:32 ExternalAuthHandler: Get : unsupported protocol scheme "",
2019/11/01 02:02:33 ExternalAuthHandler: Get : unsupported protocol scheme "",
```

## Expected Behaviour
No error

## Current Behaviour
Getting error

## Steps to Reproduce (for bugs)

1. Deploy stack docker.exe stack deploy -c [docker-compose.yml](https://github.com/openfaas/faas/blob/a39ed5534ba29be9fc78be8adc7cb4030ef15449/docker-compose.yml) faas 
2. Try to access to http://localhost:8080/ui/
3. Got error

## Context
Fresh installation return error

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 
 commit:  b7a67fe8d6a02aef35caae615ba56333e7337bfe
 version: 0.9.5

* Docker version `docker version` (e.g. Docker 17.0.05 ): Docker version 19.03.4, build 9013bf5

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS): Docker on Windows, faas-cli on linux

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment] 2019-11-01 11:44
Did you guys disable basic auth perhaps?

**Comment by alexellis** [comment] 2019-11-01 11:48
I've taken a look into this and cannot reproduce any errors.

Here's the deployment working fine:

![Screenshot 2019-11-01 at 11 46 47](https://user-images.githubusercontent.com/6358735/68022834-5f460480-fc9d-11e9-8643-80186bc26bc7.png)

And accessing dashboard working fine too including a function

![Screenshot 2019-11-01 at 11 47 08](https://user-images.githubusercontent.com/6358735/68022845-6836d600-fc9d-11e9-93aa-b13ff47e5851.png)

How can I reproduce what you have? Show me and I'll try to help.

**Comment by steevegldev** [comment] 2019-11-01 11:48
> Did you guys disable basic auth perhaps?

How to do that?

I deployed faas services by using the docker compose file. All options are by default.

**Comment by alexellis** [comment] 2019-11-01 11:49
I take it you are using `deploy_stack.sh` as instructed right? Where did you get `docker-compose.exe` from?

https://docs.openfaas.com/deployment/docker-swarm/#20-deploy-the-stack

**Comment by alexellis** [comment] 2019-11-01 11:52
I'm going to close the issue due to the non-standard installation and I can't reproduce the error.

Please use the installation method provided for you.

Feel free to keep commenting if you need additional technical support after you've used the supported installation method.

**Closed** 2019-11-01 11:51 UTC
Labels: good first issue, need/more-info, question, support

**Comment by steevegldev** [comment] 2019-11-01 12:27
I did not notice the deploy script because it's not common to do that to deploy a compose file. So, it's working now.

The confusion is from (Portainer's template)[https://github.com/portainer/templates]. They use directly the compose file and the deployment doesn't work.

Thanks

**Comment by alexellis** [comment] 2019-11-01 13:40
We do have a problem with the compose file then, since it should still fall back to defaults. @LucasRoesler ptal?
